### PR TITLE
19 example resource

### PR DESCRIPTION
**Pull request by lpg-tech**
Beispiel für Organisation, Patient, Practitioner, laufen fehlerfrei durch, ebenso
serviceRequest/lab.xml, und questionnaire/chemogram hematology und 1-tvt, falls du noch validieren möchtest.

### CODE REVIEW

**Comment by isels1** [comment]
ready to merge when errors in referral-min.xml will get resolved:
image

**Review by ganimedes — APPROVED** [review]
Publisher passes without errors

**Review by ganimedes — APPROVED** [review]
Publisher pass withour errors

**Comment by isels1** [comment]
0 errors during building. merging now

**Review by isels1 — APPROVED** [review]

**Pull request merged**
